#config-file

# este arquivo pode ser utilizado como modelo para criação de outras aplicações. 
# Os templates contidos na pasta templates podem ser customizados de acordo com cada aplicação.
namespace: apps-dev

app:
  name: netcore-sample 
  deploymentName: netcore-sample 
  deploymentConfigMatch: "netcore-sample" 
  version: "v1" 
  persistentVolumeClaim: 
    enabled: false

configmap:
  enabled: true
  items:
    - name: netcore-config
      filePath: "files/appsettings.json"
      fileName: appsettings.json

secrets:
  - name: netcore-sample-secrets
    keys:
      - name: EXAMPLE_DB_PASS
        encoded: false
        value: "admin"

replicaCount: 1

image:
  nameVersion: image-registry.openshift-image-registry.svc:5000/apps-dev/netcore-sample:1.0.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "netcore-sample"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  - containerPort: 8080

#resources:
#  limits:
#    cpu: 600m
#    memory: 1Gi
#  requests:
#    cpu: 10m
#    memory: 128Mi

environments:
  - name: EXAMPLE_DB_HOST
    value: "postgresql.databases.svc.cluster.local"
  - name: EXAMPLE_DB_PORT
    value: "5432"
  - name: EXAMPLE_DB_PASS
    valueFrom:
      secretKeyRef:
        name: netcore-sample-secrets
        key: EXAMPLE_DB_PASS

volumes:
  - name: netcore-config
    configMap:
      name: netcore-config

volumeMounts:
  - name: netcore-config
    mountPath: "/opt/app-root/app/appsettings.json"
    subPath: appsettings.json

service:
  type: NodePort
  name: http
  port: 8080
  targetPort: 8080

route:
  enabled: true  
  host: netcore-apps-dev.apps.opsprd.solarbr.com.br

# definição de probes de health-check
#readinessProbe:
#  httpGet:
#    path: /actuator/health/readiness
#    port: 8080
#    scheme: HTTP
#  initialDelaySeconds: 20
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

#livenessProbe:
#  httpGet:
#    path: /actuator/health/liveness
#    port: 8080
#    scheme: HTTP
#  initialDelaySeconds: 20
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3
