{{- if and .Values.gitAuth.secretName .Values.pipelineNamespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitAuth.secretName }}
  namespace: {{ .Values.pipelineNamespace }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: ""
  password: ""
{{- end }}
