{{- if and .Values.gitAuth.secretName .Values.pipelineNamespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: {{ .Values.pipelineNamespace }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: ""
  password: ""
{{- end }}

{{ if .Values.pipelinesv2 }}
{{ range $pipeline := .Values.pipelinesv2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: {{ $pipeline.projectOcName }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.gitAuth.gitUsername | quote }}
  password: {{ .Values.gitAuth.gitPassword | quote }}
{{ end }}
{{ end }}

{{ if .Values.pipeMoveImage }}
{{ range $pipeline := .Values.pipeMoveImage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: {{ $pipeline.projectToName }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.gitAuth.gitUsername | quote }}
  password: {{ .Values.gitAuth.gitPassword | quote }}
{{ end }}
{{ end }}
