apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
  namespace: {{ .Values.pipelineNamespace }}
  annotations:
    tekton.dev/docker-0: "https://{{ .Values.externalRegistry.host }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.externalRegistry.dockerconfig | quote }}