{{ if .Values.pipelinesv2 }}
{{ range $pipeline := .Values.pipelinesv2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: roxctl-secret
  namespace: {{ $pipeline.projectOcName }}
type: Opaque
stringData:
  ROX_API_TOKEN: "{{ $.Values.roxctlScan.apiToken }}"
{{ end }}
{{ end }}

{{ if .Values.pipeMoveImage }}
{{ range $pipeline := .Values.pipeMoveImage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: roxctl-secret
  namespace: {{ $pipeline.projectToName }}
type: Opaque
stringData:
  ROX_API_TOKEN: "{{ $.Values.roxctlScan.apiToken }}"
{{ end }}
{{ end }}
