{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.route.host }}
  path: /
  tls:
    termination: edge
  to:
    name: {{ .Values.app.name }}
    kind: Service
    weight: 100
{{- end }}    