{{ if .Values.pipelinesv2 }}
{{ range $pipeline := .Values.pipelinesv2 }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-{{ $pipeline.pipeName }}
  namespace: {{ $pipeline.projectOcName }}
spec:
  params:
    - default: {{ $.Values.gitAuth.secretName }}
      name: GIT_SECRET
      type: string
    - name: GIT_HOST
      description: The git repository host
      type: string
      default: {{ $pipeline.gitHost }}
    - default: https
      name: GIT_PROTOCOL
      type: string
    - name: APP_SOURCE_GIT
      description: The application git repository
      type: string
      default: {{ $pipeline.appSourceGit }}
    - name: APP_SOURCE_BRANCH
      type: string
      default: {{ $pipeline.appSourceBranch }}
    - name: APP_SOURCE_PATH
      type: string
      default: {{ $pipeline.appSourcePath }}
    - name: APP_MANIFESTS_GIT      
      type: string
      default: {{ $pipeline.appManifestGit }}
    - name: APP_MANIFESTS_GIT_BRANCH      
      type: string
      default: {{ $pipeline.appManifestGitBranch }}       
    - default: {{ $pipeline.appManifestPath }}
      description: The application manifests git repository path
      name: APP_MANIFESTS_PATH
      type: string
    - default: {{ $pipeline.projectOcName }}
      description: The pipelines project runs
      name: PROJECT_OC_NAME
      type: string
    - name: GIT_HASH_COMMIT
      type: string
      description: The application image tag to build
      default: {{ $pipeline.gitHashCommit }}
  results:
    - description: The image digest built in the pipeline
      name: APP_NAMESPACE
      value: $(tasks.set-namespace.results.ns)
    - description: The name of branch handled
      name: APP_NAME
      value: $(tasks.app-name.results.app_name)        
  tasks:
    - name: source-clone
      params:
        - name: GIT_HOST
          value: $(params.GIT_HOST)
        - name: GIT_PROTOCOL
          value: $(params.GIT_PROTOCOL)
        - name: GIT_PATH
          value: "$(params.APP_SOURCE_GIT)"
        - name: GIT_SOURCE_BRANCH
          value: "$(params.APP_SOURCE_BRANCH)"
        - name: git-secret-name
          value: $(params.GIT_SECRET)
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-clone
          - name: namespace
            value: "{{ $pipeline.projectOcName }}"
          - name: kind
            value: task
      workspaces:
        - name: workspace
          workspace: workspace
    - name: set-namespace
      params:
        - name: PROJECT_OC_NAME
          value: $(params.PROJECT_OC_NAME)
      runAfter:
        - source-clone 
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: set-build-namespace
          - name: namespace
            value: "{{ $pipeline.projectOcName }}"
          - name: kind
            value: task
    - name: app-name
      params:               
        - name: GIT_HOST
          value: $(params.GIT_HOST)
        - name: GIT_PROTOCOL
          value: $(params.GIT_PROTOCOL)
        - name: GIT_PATH
          value: $(params.APP_MANIFESTS_GIT)  
        - name: SOURCE_BRANCH
          value: $(params.APP_MANIFESTS_GIT_BRANCH)
        - name: SOURCE_FOLDER
          value: $(params.APP_MANIFESTS_PATH)  
        - name: git-secret-name
          value: $(params.GIT_SECRET)
      runAfter:
        - set-namespace
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: set-app-name
          - name: namespace
            value: "{{ $pipeline.projectOcName }}"
          - name: kind
            value: task
      workspaces:
        - name: workspace
          workspace: workspace
    - name: build-maven
      params:
        - name: SUBDIRECTORY
          value: $(params.APP_SOURCE_PATH)
      runAfter:
        - app-name
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
      workspaces:
        - name: source
          workspace: workspace
    - name: build-image
      params:
        - name: TLS_VERIFY
          value: 'false'
        - name: IMAGE
          value: >-
             image-registry.openshift-image-registry.svc:5000/$(tasks.set-namespace.results.ns)/$(tasks.app-name.results.app_name):$(params.GIT_HASH_COMMIT)
        - name: CONTEXT
          value: $(params.APP_SOURCE_PATH)
        - name: DOCKERFILE
          value: $(params.APP_SOURCE_PATH)/src/main/docker/Dockerfile.jvm
      runAfter:
        - build-maven
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
      workspaces:
        - name: source
          workspace: workspace
    - name: update-deployment
      params:
        - name: GIT_HOST
          value: $(params.GIT_HOST)
        - name: GIT_PROTOCOL
          value: $(params.GIT_PROTOCOL)
        - name: GIT_PATH
          value: $(params.APP_MANIFESTS_GIT)  
        - name: APP_MANIFESTS_PATH
          value: $(params.APP_MANIFESTS_PATH)
        - name: GIT_HASH_COMMIT
          value: $(params.GIT_HASH_COMMIT)      
        - name: SOURCE_BRANCH
          value: $(params.APP_MANIFESTS_GIT_BRANCH)  
        - name: git-secret-name
          value: $(params.GIT_SECRET)
      runAfter:
        - build-image
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-update-deployment
          - name: namespace
            value: "{{ $pipeline.projectOcName }}"
          - name: kind
            value: task
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
{{ end }}
{{ end }}    
