apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-service-spring-dev-ci
  namespace: spring-pipeline
spec:
  params:
    - default: hello-service
      name: SOURCE_GIT_CONTEXT_DIR
      type: string
    - default: hello-service
      description: The application name
      name: APP_NAME
      type: string
    - default: hello-spring-dev
      description: Namespace where the buildconfig will be or is located
      name: NAMESPACE
      type: string
    - default: hello-spring-dev
      description: Namespace where the buildconfig will be or is located
      name: NAMESPACE_DEV
      type: string
    - default: >-
        http://example-nexusrepo-sonatype-nexus-service.nexus.svc:8081/repository/maven-public/
      description: Maven mirror for Maven Builds
      name: MAVEN_MIRROR_URL
      type: string
    - default: quay.io/demo-pipelines
      description: External Registry (Nexus) for the Images
      name: EXTERNAL_REG_NEXUS_URL
      type: string
    - default: sqp_8dab635a854801eb36f81416aa393457282f836d
      name: SONAR_AUTH_TOKEN_SCANNER
      type: string      
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/msoares94/openshift-pipeline-tekton-and-openshift-gitops'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: generate-tag
      taskRef:
        kind: Task
        name: generate-tag
    - name: jkube-build
      params:
        - name: MAVEN_IMAGE
          value: 'registry.access.redhat.com/ubi8/openjdk-11:1.3'
        - name: CONTEXT_DIR
          value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
        - name: GOALS
          value:
            - package
            - 'oc:build'
            - '-Djkube.namespace=$(params.NAMESPACE)'
            - '-Djkube.generator.name=$(params.APP_NAME)'
        - name: MAVEN_MIRROR_URL
          value: $(params.MAVEN_MIRROR_URL)
      runAfter:
        - git-clone
        - generate-tag
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: oc-tag-image-for-dev
      params:
        - name: SCRIPT
          value: >-
            oc tag $(params.NAMESPACE)/$(params.APP_NAME):latest
            $(params.NAMESPACE)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)
        - name: VERSION
          value: latest
      runAfter:
        - jkube-build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: update-kustomize-repo-dev
      params:
        - name: gitRepositoryUrl
          value: 'https://github.com/msoares94/hellosvc-kustomize-repo'
        - name: gitRepositoryRevision
          value: main
        - name: gitPath
          value: hello-service-kustomize/overlays/development
        - name: fileName
          value: deployment-patches.yaml
        - name: image
          value: hello-service
        - name: imageTag
          value: dev-\$(tasks.generate-tag.results.image-tag)
        - name: verbose
          value: 'true'
      runAfter:
        - oc-tag-image-for-dev
      taskRef:
        kind: Task
        name: update-kustomize-repo
    - name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: >-
            https://sonarqube-sonarqube.apps.cluster-vsqb4.vsqb4.sandbox2176.opentlc.com
        - name: SONAR_PROJECT_KEY
          value: $(params.APP_NAME)
        - name: SONAR_AUTH_TOKEN
          value: $(params.SONAR_AUTH_TOKEN_SCANNER)
      runAfter:
        - set-image-for-dev
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: output
    - name: push-img-to-external-registry
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE_DEV)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)
        - name: destImageURL
          value: >-
            docker://quay.io/demo-pipelines/$(params.APP_NAME):prod-$(tasks.generate-tag.results.image-tag)
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      runAfter:
        - sonarqube-scanner
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: output
    - name: update-kustomize-repo-prod
      params:
        - name: gitRepositoryUrl
          value: 'https://github.com/msoares94/hellosvc-kustomize-repo'
        - name: gitRepositoryRevision
          value: prod
        - name: gitPath
          value: hello-service-kustomize/overlays/development
        - name: fileName
          value: deployment-patches.yaml
        - name: image
          value: hello-service
        - name: imageTag
          value: prod-\$(tasks.generate-tag.results.image-tag)
        - name: verbose
          value: 'true'
      runAfter:
        - push-img-to-external-registry
      taskRef:
        kind: Task
        name: update-kustomize-repo
    - name: set-image-for-dev
      params:
        - name: ARGS
          value:
            - set
            - image
            - deployments
            - $(params.APP_NAME)
            - >-
              $(params.APP_NAME)=image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE_DEV)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)
            - '-n $(params.NAMESPACE_DEV)'
      runAfter:
        - oc-tag-image-for-dev
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: output
    - name: maven-settings
    - name: app-source