apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
spec:
  taskRef:
    kind: ClusterTask
    name: git-clone
  params:
  - name: url
    value: https://github.com/rafamqrs/demo-pipeline-tkn
  - name: revision
    value: development
  - name: deleteExisting
    value: 'true'
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: workspace-pvc
