apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Messaging
    tekton.dev/displayName: send mail
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le,linux/arm64'
    tekton.dev/tags: mail
  name: sendmail
  namespace: spring-pipeline
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: This task sends a simple email to receivers via SMTP server
  params:
    - description: 'secret name for SMTP server information (url, port, password)'
      name: server
      type: string
    - description: plain text email subject
      name: subject
      type: string
    - description: plain text email body
      name: body
      type: string
    - description: sender email address
      name: sender
      type: string
    - description: recipient email addresses (space delimited list)
      name: recipients
      type: string
  steps:
    - env:
        - name: USER
          valueFrom:
            secretKeyRef:
              key: user
              name: $(params.server)
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: $(params.server)
        - name: TLS
          valueFrom:
            secretKeyRef:
              key: tls
              name: $(params.server)
        - name: SERVER
          valueFrom:
            secretKeyRef:
              key: url
              name: $(params.server)
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: $(params.server)
      image: >-
        docker.io/library/python:3.8-alpine@sha256:e11bbd37d4371894e954421b85dbe8dd4eb7198d7cb4ed144ab529f19f57c3f1
      name: send
      resources: {}
      script: |
        #!/usr/bin/env python3
        import smtplib, ssl, os
        port = os.getenv('PORT')
        smtp_server = os.getenv('SERVER')
        sender_email = "$(params.sender)"
        receiver_emails = "$(params.recipients)"
        user = os.getenv('USER')
        password = os.getenv('PASSWORD')
        tls = os.getenv('TLS')
        message = f"""\
        Subject: $(params.subject)
        To: {receiver_emails}
        From: {sender_email}

        $(params.body)"""
        print(message)
        if tls == 'True':
            context = ssl.create_default_context()
            server = smtplib.SMTP_SSL(smtp_server, port, context=context)
        else:
            server = smtplib.SMTP(smtp_server, port)
        if password != '':
            server.login(user, password)
        for receiver in [item for item in receiver_emails.split(' ') if item]:
            server.sendmail(sender_email, receiver, message.encode('utf-8'))
        server.quit()
