apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: '2022-06-17T19:15:16Z'
  finalizers:
    - eventlisteners.triggers.tekton.dev
  name: event-listener-itktag
  namespace: spring-pipeline
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-hello-service-spring-dev-ci-fsazpc