{{- if .Values.configmap.enabled }}
{{ range $configmap := $.Values.configmap.items }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{ include "argocd.defaultLabels" . | indent 4 }}
    app: {{ $.Values.app.name }}
data:
  {{ $configmap.fileName }}: |-
{{ $.Files.Get $configmap.filePath | indent 4}}

{{- end }}
{{- end }}