{{- if .Values.app.persistentVolumeClaim.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Values.app.name }}-data-disk'
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
{{ include "argocd.defaultLabels" . | indent 4 }}    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{end}}