{{- if .Values.pipelineNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.pipelineNamespace }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}

{{- if .Values.pipelinesv2 }}
{{- range .Values.pipelinesv2 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .projectOcName }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
{{- end }}

{{- if .Values.pipeMoveImage }}
{{- range .Values.pipeMoveImage }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .projectToName }}
  annotations:
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .projectFromName }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
{{- end }}
